version: '3'

services:
  client:
    restart: always
    build: ./client
    # ports:
    #   - 8080:8080

  database:
    platform: linux/x86_64
    restart: always
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379

  worker:
    restart: always
    build: ./worker
    environment:
      DEVELOPER_KEY: ${DEVELOPER_KEY}
    depends_on:
      - redis
      - database

  api:
    restart: always
    build: ./server
    # ports:
    #   - 6060:5000
    depends_on:
      - database
  
  nginx:
    restart: always
    depends_on:
      - api
      - client
    build: ./nginx
    ports:
      - 80:80
